org: michaeleguruze
app: aws-node-http-api
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  dftRecord:
    handler: getTrafficRecord.handler
    events:
      - httpApi:
          path: /count-point-id/{id}
          method: get
